# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Leansquad_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Leansquad_test

pod 'SwiftKeychainWrapper'

pod 'Alamofire', '~>5.0'
pod 'AlamofireNetworkActivityLogger'

end
